### ISSUE TITLE
Transform upgrades file has `bus` and `buses`

### ISSUE THREAD

**Issue by daniel-thom** [NREL/disco#125]
The file `transformer_upgrades.json` reports an array of transformer objects. Each of those objects has a `bus` field as well as a `buses` field. What is the difference? Does `bus` need to be there?

Is this also tied to the fields kV, kVs, kVA, kVAs, conn, conns?

**Comment by daniel-thom** [comment]
One possible solution is to separate disco parameters from OpenDSS parameters. There can be a sub-object called `opendss_parameters`.

**Comment by ann-sherin** [comment]
->A lot of these fields are opendss names. So, I think it should be fine to let it stay. Can add documentation on the additional fields added.

->Also, would prefer not changing the structure since this json is converted in a table, while computing costs. And the parameters are accessed from the table.
